export let englishContent = [
	"Introduce",
	"Works",
	"Testimonials",
	"Services",
	"Contact",
	"Blog",
	"Elevate Your Digital Presence with me",
	"Welcome to my digital world, where innovation and functionality converge to create exceptional web experiences. As a seasoned full stack web developer, I specialize in transforming your ideas into seamless, user-friendly websites.",
	"WORK WITH ME !",
	"Frontend",
	"I specialize in creating captivating user interfaces through expert use of HTML, CSS, JavaScript, Bootstrap and Sass delivering seamless and engaging website experiences.",
	"Backend",
	"With expertise in server-side scripting and database management, I architect with PHP and MySQL, robust backend systems that power websites with efficiency and reliability.",
	"WordPress",
	"I leverage the flexibility of WordPress to craft dynamic websites with custom themes and plugins, marrying design with functionality for a seamless user experience.",
	"SEO",
	"My SEO proficiency ensures your website not only looks great but also ranks well, driving targeted organic traffic through strategic optimization techniques.",
	"Introduce",
	"Hello! I'm Abdelkarim Achlaih",
	"Every great development begins with a clear vision, meticulous planning, and a commitment to turning ideas into elegant, functional solutions.",
	"Your ally in the realm of web development. In a world saturated with cookie-cutter websites, I bring a breath of fresh air. My two years of experience as a full stack web developer empower me to craft tailored solutions that speak to your unique project requirements.",
	"Latest Works",
	"Perfect solutions for digital experience",
	"Fylo Website",
	"Live Demo",
	"View Code",
	"Blog Website",
	"Live Demo",
	"View Code",
	"Github Repos App",
	"Live Demo",
	"View Code",
	"Currency Converter",
	"Live Demo",
	"View Code",
	"Gaming Template",
	"Live Demo",
	"View Code",
	"All projects",
	"* Browse other projects on ",
	"my GitHub",

	"Testimonials",
	"What's my clients, friends say about me",
	"We would like to express our heartfelt gratitude for your outstanding work in developing our official website at <a target='_blank' href='https://stara-immo.rf.gd/'>STARAIMMO</a>. Your dedication and expertise in creating our digital presence have greatly contributed to enhancing our online reach and showcasing our services effectively. Your commitment to excellence is truly commendable, and we are fortunate to have had you as part of our team. Thank you for your exceptional contributions.",
	"One of the most impressive aspects of Abdelkarim's work is their commitment to creating solutions that are both aesthetically pleasing and highly functional. Their keen eye for design, coupled with their coding finesse, results in websites and web applications that not only look fantastic but also deliver exceptional user experiences. Abdelkarim understands that the digital landscape is as much about visual appeal as it is about performance, and they strike the perfect balance between the two.",

	"Engineer, Friend",
	"My Services",
	"Empowering your digital journey with innovative solutions that leave a lasting impression",
	"Search Engine Optimization (SEO)",
	"Ignite your online presence with a tailored SEO strategy that puts your website on the digital map. Using an array of proven techniques, I enhance your website's visibility on search engines, ensuring that your target audience can easily find you. From comprehensive keyword research and strategic content optimization to technical improvements and authoritative link building, my SEO services are designed to drive organic traffic, boost rankings, and maximize your online impact. Let's collaborate to unlock the full potential of your website in the ever-evolving digital landscape.",
	"Order Now",
	"Websites for businesses",
	"You are an inhouse/agency marketer or a business manager, you want to build an awareness of your brand and generate more leads, feeling overwhelmed by technology jargon, and you don’t have the capacity to build an inhouse IT service, I'm here to demystify complex concepts, guiding you through the technical landscape to make informed decisions that align with your marketing strategy. My websites are designed to captivate your audience and turn visitors into loyal customers. Let's transform your business into a digital success story, one pixel at a time.",
	"Order Now",
	"E-Commerce Solutions",
	"Elevate your online store into a captivating shopping destination that converts browsers into buyers. I specialize in creating tailored e-commerce solutions that prioritize user experience and drive sales. From intuitive navigation and eye-catching product displays to secure payment gateways and streamlined checkout processes, every aspect of your e-commerce store is optimized for success. Collaborate with me to transform your online shop into a digital marketplace that not only attracts customers but keeps them coming back for more.",
	"Order Now",
	"Custom Websites for Students, Bloggers, and Artists",
	"Empower your creative journey with personalized websites designed to showcase your talents and aspirations. Whether you're a student building a portfolio, a blogger sharing your thoughts, or an artist displaying your work, I specialize in crafting custom websites that amplify your unique voice. From seamless navigation that presents your content effortlessly to design elements that reflect your personality, I create online spaces that resonate with your target audience. Let's collaborate to transform your digital presence into a canvas that captures your essence and captivates your audience.",
	"Order Now",
	"PSD or Figma to Web Page or WordPress Theme",
	"Bring your design concepts to life with precision and elegance. I specialize in converting your PSD or Figma files into fully functional web pages or WordPress themes, ensuring pixel-perfect accuracy and maintaining the integrity of your design. Seamlessly blending aesthetics with functionality, I bridge the gap between design and development, creating a seamless user experience that reflects your original vision. Let's turn your creative designs into interactive digital masterpieces that captivate your audience.",
	"Order Now",
	"Web Application Development",
	"Elevate your business processes with custom web applications designed to streamline operations and enhance user experiences. Whether it's an internal tool to boost efficiency or a customer-facing platform that offers unique functionality, I specialize in developing web applications that cater to your specific needs. From interactive dashboards and data visualization tools to seamless integrations with existing systems, I turn complex ideas into intuitive solutions that drive growth and innovation. Collaborate with me to bring your web app vision to life and revolutionize the way you do business online.",
	"Order Now",

	"Let's make something amazing together.",
	"Start by saying hi",
	"Name",
	"Email",
	"Message",
	"© 2023, All Rights Reserved",
	"Design inspired from  <a href='https://dribbble.com/shots/11276631-DS-Personal-Developer-Portfolio'>Logan Cee</a>",
	"",
	"",
	"",
	"",
];
export let frenchContent = [
	"Introduire",
	"Travaux",
	"Témoignages",
	"Services",
	"Contact",
	"Blog",
	"Améliorez votre présence numérique avec moi",
	"Bienvenue dans mon monde numérique, où l'innovation et la fonctionnalité convergent pour créer des expériences web exceptionnelles. En tant que développeur web expérimenté, je me spécialise dans la transformation de vos idées en sites web transparents et conviviaux.",
	"TRAVAILLEZ AVEC MOI !",
	"Frontend",
	"Je suis spécialisée dans la création d'interfaces utilisateur captivantes grâce à l'utilisation experte de HTML, CSS, JavaScript, Bootstrap et Sass, ce qui permet de créer des sites Web transparents et attrayants.",
	"Backend",
	"Grâce à mon expertise dans le domaine des scripts côté serveur et de la gestion des bases de données, je conçois, avec PHP et MySQL, des systèmes dorsaux robustes qui alimentent les sites web avec efficacité et fiabilité.",
	"WordPress",
	"J'exploite la flexibilité de WordPress pour créer des sites web dynamiques avec des thèmes et des plugins personnalisés, en mariant le design et la fonctionnalité pour une expérience utilisateur transparente.",
	"Référencement Web",
	"Mes compétences en matière de référencement garantissent que votre site Web ne se contente pas d'avoir une belle apparence, mais qu'il se classe également bien, en générant un trafic organique ciblé grâce à des techniques d'optimisation stratégiques.",
	"Introduire",
	"Bonjour ! Je suis Abdelkarim Achlaih",
	"Tout grand projet de développement commence par une vision claire, une planification méticuleuse et un engagement à transformer les idées en solutions élégantes et fonctionnelles.",
	"Votre allié dans le domaine du développement web. Dans un monde saturé de sites web à l'emportepièce, j'apporte une bouffée d'air frais. Mes deux années d'expérience en tant que développeur web full stack me permettent de concevoir des solutions sur mesure qui répondent aux exigences uniques de votre projet.",

	"Derniers travaux",
	"Des solutions parfaites pour l'expérience numérique",

	"Site web Fylo",
	"Démonstration en direct",
	"Voir le code",

	"Site web de blog",
	"Démonstration en direct",
	"Voir le code",

	"Application GitHub",
	"Démonstration en direct",
	"Voir le code",

	"Converteur de devises",
	"Démonstration en direct",
	"Voir le code",

	"Gaming template",
	"Démonstration en direct",
	"Voir le code",

	"Tous les projets",
	"* Parcourir d'autres projets sur ",
	"mon GitHub",
	"Témoignages",
	"Ce que mes clients et amis disent de moi",
	"Nous tenons à vous exprimer notre sincère gratitude pour le travail remarquable que vous avez accompli en développant notre site web officiel à <a target='_blank' href='https://stara-immo.rf.gd/'>STARA IMMO</a>. Votre dévouement et votre expertise dans la création de notre présence numérique ont grandement contribué à améliorer notre portée en ligne et à mettre en valeur nos services de manière efficace. Votre engagement en faveur de l'excellence est vraiment louable, et nous avons la chance de vous compter parmi les membres de notre équipe. Nous vous remercions pour votre contribution exceptionnelle.",
	"L'un des aspects les plus impressionnants du travail d'Abdelkarim est son engagement à créer des solutions à la fois esthétiques et hautement fonctionnelles. Leur sens aigu du design, associé à leur finesse de codage, se traduit par des sites et des applications web qui non seulement sont fantastiques, mais qui offrent également une expérience utilisateur exceptionnelle. Abdelkarim comprend que le paysage numérique est autant une question d'attrait visuel que de performance, et il trouve l'équilibre parfait entre les deux.",
	"Ingénieur, Ami",
	"Mes services",
	"Des solutions innovantes qui laissent une impression durable à votre parcours numérique",
	"Optimisation pour les moteurs de recherche (SEO)",
	"Dynamisez votre présence en ligne grâce à une stratégie de référencement sur mesure qui place votre site web sur la carte numérique. En utilisant un ensemble de techniques éprouvées, j'améliore la visibilité de votre site web sur les moteurs de recherche, en veillant à ce que votre public cible puisse vous trouver facilement. De la recherche complète de mots-clés à l'optimisation stratégique du contenu, en passant par les améliorations techniques et la création de liens d'autorité, mes services de référencement sont conçus pour générer du trafic organique, améliorer les classements et maximiser votre impact en ligne. Collaborons pour libérer le plein potentiel de votre site web dans le paysage numérique en constante évolution.",
	"Commander",
	"Sites web pour les entreprises",
	"Vous êtes un spécialiste du marketing interne/agence ou un chef d'entreprise, vous voulez faire connaître votre marque et générer plus de prospects, vous vous sentez dépassé par le jargon technologique, et vous n'avez pas la capacité de créer un service informatique interne, je suis là pour démystifier les concepts complexes, vous guider dans le paysage technique pour prendre des décisions éclairées qui s'alignent sur votre stratégie de marketing. Mes sites web sont conçus pour captiver votre public et transformer les visiteurs en clients fidèles. Transformons votre entreprise en un succès numérique, un pixel à la fois.",
	"Commander",
	"Solutions de e-commerce",
	"Transformez votre boutique en ligne en une destination d'achat captivante qui convertit les navigateurs en acheteurs. Je suis spécialisée dans la création de solutions de commerce électronique sur mesure qui donnent la priorité à l'expérience utilisateur et stimulent les ventes. De la navigation intuitive à la présentation attrayante des produits, en passant par les passerelles de paiement sécurisées et les processus de paiement simplifiés, chaque aspect de votre boutique en ligne est optimisé pour le succès. Collaborez avec moi pour transformer votre boutique en ligne en une place de marché numérique qui non seulement attire les clients, mais les incite à revenir.",
	"Commander",
	"Sites web personnalisés pour étudiants, blogueurs et artistes",
	"Donnez du poids à votre parcours créatif grâce à des sites web personnalisés conçus pour mettre en valeur vos talents et vos aspirations. Que vous soyez un étudiant qui se constitue un portfolio, un blogueur qui partage ses idées ou un artiste qui expose son travail, je suis spécialisée dans la création de sites web personnalisés qui amplifient votre voix unique. De la navigation transparente qui présente votre contenu sans effort aux éléments de conception qui reflètent votre personnalité, je crée des espaces en ligne qui résonnent avec votre public cible. Collaborons pour transformer votre présence numérique en une toile qui capture votre essence et captive votre public.",
	"Commander",
	"PSD ou Figma vers une page web ou un thème WordPress",
	"Donnez vie à vos concepts de design avec précision et élégance. Je me spécialise dans la conversion de vos fichiers PSD ou Figma en pages web ou thèmes WordPress entièrement fonctionnels, en garantissant une précision au pixel près et en préservant l'intégrité de votre design. Alliant harmonieusement l'esthétique et la fonctionnalité, je comble le fossé entre le design et le développement, en créant une expérience utilisateur transparente qui reflète votre vision originale. Transformons vos conceptions créatives en chefs-d'œuvre numériques interactifs qui captiveront votre public.",
	"Commander",
	"Développement d'applications web",
	"Améliorez vos processus d'entreprise grâce à des applications web personnalisées conçues pour rationaliser les opérations et améliorer l'expérience des utilisateurs. Qu'il s'agisse d'un outil interne destiné à améliorer l'efficacité ou d'une plateforme destinée aux clients et offrant des fonctionnalités uniques, je me spécialise dans le développement d'applications web qui répondent à vos besoins spécifiques. Qu'il s'agisse de tableaux de bord interactifs, d'outils de visualisation de données ou d'intégrations transparentes avec des systèmes existants, je transforme des idées complexes en solutions intuitives qui stimulent la croissance et l'innovation. Collaborez avec moi pour donner vie à votre vision de l'application web et révolutionner la façon dont vous faites des affaires en ligne.",
	"Commander",
	"Réalisons ensemble quelque chose d'extraordinaire.",
	"Commencez par dire bonjour",
	"Nom",
	"Email",
	"Message",
	"2023, tous droits réservés",
	"Design inspiré de <a href='https://dribbble.com/shots/11276631-DS-Personal-Developer-Portfolio'>Logan Cee</a>",
];
